[workspace]
members = [
	'crates/fs',
	'crates/wasm'
]

[patch.crates-io]
libipld = { git = "https://github.com/appcypher/libipld", branch = "appcypher/expose-ipld-serializer" }
skip_ratchet = { git = "https://github.com/wnfs-wg/rs-skip-ratchet", branch = "matheus23/seek" }
